# Generated by Django 5.2.7 on 2026-01-02 04:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="status",
            new_name="userStatus",
        ),
        migrations.RenameField(
            model_name="task",
            old_name="status",
            new_name="taskStatus",
        ),
        migrations.AlterField(
            model_name="task",
            name="task_manager",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks_managed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="teams_managed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
